name: Lint & Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black isort
        
    - name: Check formatting with Black
      run: black . --check --diff --line-length=88
        
    - name: Check imports with isort
      run: isort . --check-only --diff --profile black
        
    - name: Lint with Ruff
      run: ruff check . 